apiVersion: v1
kind: PersistentVolume
metadata:
  name: eventservice-images-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/eventservice-images"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eventservice-images-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
